<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2021-07-03 18:40:18
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'all-d12dc5308cede8228d174b11eaf7dd52.js',
        ],
        'sourcePath' => null,
        'css' => [],
        'depends' => [],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [ 'css/normalize.css',
            'css/style.css',
            'css/task-force.css',],
        'depends' => [
            'yii\\web\\YiiAsset',
            'all',
        ],
    ],
    'frontend\\assets\\LandingAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [ 'css/normalize.css',
            'css/style.css',
            'css/task-force.css',],
        'depends' => [
            'yii\\web\\YiiAsset',
            'all',
        ],
    ],
    'frontend\\assets\\TaskCreateAsset' => [
        'js' => [
            'js/autoComplete.min.js',
            'js/autoComplete.init.js',
            'js/messenger.js',
        ],
        'css' => [
            'css/js-plugin.css',
        ],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\TaskCreateAsset',
    ],
    'frontend\\assets\\TaskViewAsset' => [
        'js' => [
            'js/main.js',
            'js/vue.js',
            'js/messenger.js',
        ],
        'depends' => [
            'yii\\web\\YiiAsset',
        ],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\TaskViewAsset',
    ],
];